#!/bin/bash
#
# SignIt
# Signs a mod package for release
#
# Copyright (C) 2010  userdelroot r00t316@gmail.com
#
# Credit to: Austen Dicken (cvpcs) for some of the code below
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# set our out target host location
OUT_TARGET_HOST=$(uname -a | grep "Darwin")
if [ -z "${OUT_TARGET_HOST}" ] ; then
    OUT_TARGET_HOST="linux-x86"
    MD5="md5sum"
else
    OUT_TARGET_HOST="darwin-x86"
    MD5="md5"
fi

PKG=$1

# time for signing!
echo "Signing: [`pwd`/${PKG}]"
java -Xmx2048m \
    -jar "${ANDROID_BUILD_TOP}/out/host/${OUT_TARGET_HOST}/framework/signapk.jar" \
    -w "${ANDROID_BUILD_TOP}/build/target/product/security/testkey.x509.pem" \
    "${ANDROID_BUILD_TOP}/build/target/product/security/testkey.pk8" \
    "`pwd`/${PKG}" "`pwd`/update-signed.zip"

# time for release!
    md5sum "update-signed.zip" \
    > "update-signed.md5sum"
MD5SUM=$(cat "update-signed.md5sum" | awk '{print $1}')

echo "Released: [update-signed.zip]"
echo "MD5: [${MD5SUM}]"
exit 0
